### ISSUE TITLE
Sacrificial Pact takes screenshot

### ISSUE THREAD

**Issue by masterkain** [italobarboza/nostalgia#5]
I was going a bit nuts but eventually found out.

if you are playing a death knight in the left tree you can select Sacrificial Pact, which kills your pet for some healing, this makes the addon take a screenshot because it's a `PARTY_KILL` event

![Screenshot 2024-08-15 081912](https://github.com/user-attachments/assets/7da3d262-a772-4832-bf47-57c8bea2517b)

**Comment by masterkain** [comment]
for pvp maybe it's better just to take screenshot of the final boards of arena/battlegrounds when the match/round ends

**Comment by italobarboza** [comment]
Hello @masterkain how are you? I hope you are doing great.
For me, your bug report it's very special, It's my first open source project and you are my very first issue reporter. I really appreciate it and I hope to fix that soon.
There is other bugs that I'm fixing this days I'm this one I was not track of. Really thank you. Probably it must happen too with other spec that have some kind of similar behavior in killing their pets. I don't play with warlock, but I guess that it has some interaction with this mechanic too. I'll test it more.

**Comment by italobarboza** [comment]
Another thing that I'll like to point it out is that I've created this project just with a fun purpose and to try Lua for the first time in my life. I'm really lost, mainly because I'm really blind with the documentation and all of the events that I can capture in the game, other issue that I'm having is debugging. For this print, it looks like you have some knowledge about the events and parameters to capture. How can I do that? Do you know any better documentation that the wowpedia? Any class that I can learn more about this environment?

Thank you

**Comment by masterkain** [comment]
hey it's no problem, just testing things out

keep in mind my knowledge is limited too, I can point some links in the hope they can be useful

- https://www.townlong-yak.com/framexml/beta (generated lua api)
- https://github.com/Ketho/vscode-wow-api (wow api addon for vscode)
- https://warcraft.wiki.gg/wiki/Patch_11.0.0/API_changes (for addon upgrades)
- https://www.curseforge.com/wow/addons/devtool (in-game event monitor)
- https://gist.githubusercontent.com/masterkain/3886b00ef401d83e0caf2213bc4fc2f1/raw/512bff164ece9dcaf5fa842d7aa9e9cec9116827/gistfile1.txt (old memoria addon from which we can pick some useful events)

**Comment by italobarboza** [comment]
Thank you my dude. Every help it's a move in the right direction. BTW, if you agree, on the next version I'll create a tab with some acknowledgments. If you are interested, I'll be pleasured in add your name, battletag or character name (and realm) if you want to. Just comment here and I'll close this issue on the PR with all this features and fixes in the next days.

**Comment by italobarboza** [comment]
Fixed on new version.

**Comment by italobarboza** [comment]
Fixed on new version.
